
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: make
  displayName: 'Run make to generate the files.'
# - task: CopyFiles@2
#   inputs:
#     sourceFolder: 'dist'
#     contents: '**/?(*.js|*.data)'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/zoneinfo-$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/zoneinfo-$(Build.BuildId).zip'
    artifactName: zoneinfo_data
